draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
from lab_1.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index)
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_list_json

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'^delete-friend/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
     url(r'^daftar-teman/$', friend_list, name='daftar-teman'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^lab-10/', include(lab_10,namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='/lab-10/', permanent = 'True'), name='index'),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

class Mahasiswa(models.Model):
    nama = models.CharField(max_length=100)
    npm = models.CharField(max_length=20)

lab_7/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.models import model_to_dict
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend, Mahasiswa
from api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()

    for mahasiswa in mahasiswa_list:
        nama_mhs = mahasiswa['nama']
        npm_mhs = mahasiswa['npm']
        Mahasiswa.objects.get_or_create(nama=nama_mhs, npm=npm_mhs)

    friend_list = Friend.objects.all()
    list_mahasiswa = Mahasiswa.objects.all()
    paginator = Paginator(list_mahasiswa, 10) # Show 10 contacts per page

    page = request.GET.get('page')
    try:
        mahasiswa_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        mahasiswa_page = paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range (e.g. 9999), deliver last page of results.
    #     mahasiswa_page = paginator.page(paginator.num_pages)
    response['friend_list'] = friend_list
    html = 'lab_7/lab_7.html'
    response['list_mahasiswa'] = mahasiswa_page
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request):
    friends = Friend.objects.all()
    friend_list = []

    for friend in friends:
        friend_list.append(model_to_dict(friend))

    daftar = {'friend_list' : friend_list}
    return JsonResponse(daftar)

def isNpmValid(npm):
    friends = Friend.objects.all()

    for friend in friends:
        if friend.npm == npm:
            return False

    return True

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        valid = isNpmValid(npm)
        data = {"isValid" : valid}

        if(data["isValid"]):
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data['friend'] = model_to_dict(friend)

        return JsonResponse(data)


@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        friend_id = request.POST['id']
        Friend.objects.filter(id=friend_id).delete()
        data = {'id' : friend_id}
        return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': not isNpmValid(npm) #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            // lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:get-friend-list" %}",
                dataType: 'json',
                success: function (response) {
                  friend_list = response['friend_list']
                    for (var i=0; i < friend_list.length; i++) {
                      friend = friend_list[i];
                      html = '<a class="list-group-item clearfix" id=' + friend.id + '>' +
                          friend.friend_name + ' (' + friend.npm + ')'
                          '</a>';
                      button = '<button onclick=deleteFriend(' + friend.id + ')> Delete </button>';
                      $("#friend-list").append(html + button)
                    }
                },
                error: function(error){
                    // #tampilkan pesan error
                }
            });
        });

        var deleteFriend = function(id) {
          $.ajax({
            method : 'POST',
            url : "{% url 'lab-7:delete-friend' %}",
            data : {'id' : id},
            dataType : 'json',
            success : function(response) {
              $('#' + response.id).hide()
            },
            error : function(error) {
              alert('error')
            }
          });
        };
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if list_mahasiswa %}
                        {% for mahasiswa in list_mahasiswa %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                                  <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                      Tambah sebagai teman
                                  </span>
                                </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix" onClick="deleteFriend('{{friend.npm}}')">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if list_mahasiswa.has_previous %}
                    <a href="?page={{ list_mahasiswa.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ list_mahasiswa.number }} of {{ list_mahasiswa.paginator.num_pages }}.
                </span>

                {% if list_mahasiswa.has_next %}
                    <a href="?page={{ list_mahasiswa.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
var addFriend = function(nama, npm) {
    $.ajax({
        method: "POST",
        url: "{% url "lab-7:add-friend" %}",
        data: { name: nama, npm: npm},
        success : function (data) {
          if(data.isValid)
          {
            html = '<a class="list-group-item clearfix">' +
                data.friend.friend_name +
                " ("+ data.friend.npm +")" +
                '</a>';
            $("#friend-list").append(html)
            $(".alert").hide()
          }
          else
          {
            alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
          }
        },
        error : function (error) {
            alert("error")
        }
    });
};



    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}